task: Unitree-G1-Tracking-No-State-Estimation
motion_file: unitree_rl_mjlab/src/assets/motions/g1/kalari_root_height_only

env:
  num_envs: 4096

agent:
  max_iterations: 30001

export:
  input_dir: data/motions_retargeted
  output_dir: unitree_rl_mjlab/src/assets/motions/g1/kalari_root_height_only
  device: cpu
