task: Unitree-G1-Tracking-No-State-Estimation
motion_file: unitree_rl_mjlab/src/assets/motions/g1/kalari/KS-007.npz

env:
  num_envs: 4096

agent:
  max_iterations: 30001

export:
  input_dir: data/motions_retargeted_raw
  output_dir: unitree_rl_mjlab/src/assets/motions/g1/kalari
  device: cpu
